const words = [
    { word: "ecosystem", hint: "A community of interacting organisms and their environment", hint2: "It includes biotic and abiotic components" },
    { word: "biodiversity", hint: "Variety of life in a particular habitat or ecosystem", hint2: "It is important for maintaining ecological balance" },
    { word: "conservation", hint: "Protection and preservation of natural resources and environments", hint2: "It aims to prevent extinction of species" },
    { word: "sustainability", hint: "Ability to maintain ecological balance and preserve resources for future generations", hint2: "It involves meeting current needs without compromising future ones" },
    { word: "pollution", hint: "Introduction of harmful substances into the environment", hint2: "It can affect air, water, and soil quality" },
    { word: "deforestation", hint: "The removal of trees and forests for land use or timber", hint2: "It leads to habitat loss and climate change" },
    { word: "global warming", hint: "Long-term increase in Earth's average temperature due to human activities", hint2: "It is primarily caused by greenhouse gas emissions" },
    { word: "climate change", hint: "Significant changes in global or regional climate patterns over time", hint2: "It is a consequence of human-induced greenhouse gas emissions" },
    { word: "greenhouse gases", hint: "Gases that trap heat in the Earth's atmosphere, leading to global warming", hint2: "Carbon dioxide and methane are the most common greenhouse gases" },
    { word: "carbon footprint", hint: "The amount of carbon dioxide emissions caused by human activities", hint2: "It is used to measure the environmental impact of an individual or organization" },
    { word: "renewable energy", hint: "Energy sourced from resources that are naturally replenished", hint2: "Examples include solar, wind, and hydroelectric energy" },
    { word: "solar energy", hint: "Energy from the sun, harnessed through solar panels", hint2: "It is one of the cleanest sources of renewable energy" },
    { word: "wind energy", hint: "Energy generated from the movement of air using wind turbines", hint2: "It is a renewable and eco-friendly power source" },
    { word: "hydroelectric energy", hint: "Energy generated from flowing water, typically through dams", hint2: "It is a major source of renewable energy worldwide" },
    { word: "sustainable development", hint: "Development that meets the needs of the present without compromising future generations", hint2: "It integrates economic, social, and environmental aspects" },
    { word: "recycling", hint: "The process of converting waste materials into reusable materials", hint2: "It helps reduce waste and conserve natural resources" },
    { word: "biodegradable", hint: "Substances that can be broken down naturally by microorganisms", hint2: "These substances do not cause long-term environmental damage" },
    { word: "waste management", hint: "The collection, disposal, and recycling of waste materials", hint2: "Effective waste management is crucial for environmental health" },
    { word: "overpopulation", hint: "Excessive population growth that leads to resource depletion", hint2: "It can result in overcrowding and environmental degradation" },
    { word: "overfishing", hint: "Depleting fish populations due to excessive fishing", hint2: "It threatens aquatic biodiversity and disrupts ecosystems" },
    { word: "conservation of biodiversity", hint: "Efforts to protect and maintain the variety of life on Earth", hint2: "It includes protecting endangered species and their habitats" },
    { word: "protected areas", hint: "Geographic areas designated for conservation and protection of wildlife", hint2: "National parks and wildlife reserves are examples" },
    { word: "endangered species", hint: "Species at risk of extinction due to environmental or human factors", hint2: "They require urgent protection to prevent their extinction" },
    { word: "habitat destruction", hint: "The process of damaging or destroying natural habitats", hint2: "It is primarily caused by human activities like deforestation" },
    { word: "ecosystem services", hint: "The benefits humans receive from ecosystems, such as clean air and water", hint2: "Pollination, climate regulation, and water purification are examples" },
    { word: "afforestation", hint: "The process of planting trees to restore or create new forests", hint2: "It helps in carbon sequestration and biodiversity conservation" },
    { word: "reforestation", hint: "Replanting trees in areas where forests have been depleted", hint2: "It is important for restoring ecological balance" },
    { word: "natural resources", hint: "Resources provided by nature, such as water, minerals, and fossil fuels", hint2: "They are limited and need to be managed sustainably" },
    { word: "sustainable agriculture", hint: "Farming practices that preserve the environment and maintain productivity", hint2: "It promotes soil health and reduces chemical use" },
    { word: "organic farming", hint: "Farming without the use of synthetic pesticides or fertilizers", hint2: "It focuses on sustainable practices and environmental protection" },
    { word: "pollinator", hint: "An organism, often an insect, that helps plants reproduce by transferring pollen", hint2: "Bees and butterflies are common pollinators" },
    { word: "ecosystem restoration", hint: "The process of restoring damaged ecosystems to their original state", hint2: "It involves replanting, rebuilding habitats, and removing pollution" },
    { word: "conservation biology", hint: "Scientific study focused on protecting biodiversity and natural resources", hint2: "It includes efforts to preserve species, genes, and ecosystems" },
    { word: "clean energy", hint: "Energy derived from renewable sources that have minimal environmental impact", hint2: "Wind, solar, and hydroelectric energy are clean energy sources" },
    { word: "carbon neutral", hint: "Achieving a net zero carbon footprint through reducing and offsetting emissions", hint2: "It involves balancing carbon emissions with carbon removal efforts" },
    { word: "climate action", hint: "Efforts to reduce global warming and mitigate climate change impacts", hint2: "This includes reducing emissions, promoting renewable energy, and protecting ecosystems" },
    { word: "carbon trading", hint: "A market-based approach to reducing emissions by allowing companies to trade carbon credits", hint2: "It aims to reduce overall greenhouse gas emissions" },
    { word: "green technology", hint: "Innovative technology designed to reduce environmental impact and promote sustainability", hint2: "Solar panels, wind turbines, and electric vehicles are examples" },
    { word: "environmental education", hint: "Teaching people about environmental issues and the importance of conservation", hint2: "It helps raise awareness about environmental protection" },
    { word: "pollution control", hint: "Strategies and actions to reduce or eliminate pollution from various sources", hint2: "It includes measures to clean up air, water, and land pollution" },
    { word: "wilderness", hint: "Undeveloped and uninhabited natural land, often important for biodiversity", hint2: "It provides habitat for wildlife and contributes to ecosystem health" },
    { word: "sustainable fisheries", hint: "Fishing practices that maintain healthy fish populations and ecosystems", hint2: "It involves setting catch limits and protecting marine habitats" },
    { word: "marine conservation", hint: "Efforts to protect and conserve the world's oceans and marine life", hint2: "It includes protecting coral reefs, reducing pollution, and sustainable fishing" },
    { word: "water conservation", hint: "Efforts to use water efficiently and reduce wastage", hint2: "It includes using water-saving technologies and practices" },
    { word: "biomass energy", hint: "Energy derived from organic materials, such as plants and animal waste", hint2: "It is considered a renewable energy source" },
    { word: "carbon sequestration", hint: "The process of capturing and storing carbon dioxide to reduce atmospheric levels", hint2: "It can be done through afforestation and soil management" },
    { word: "earth day", hint: "An annual event dedicated to environmental protection and raising awareness", hint2: "It is celebrated on April 22 every year" },
    { word: "greenhouse effect", hint: "The warming of the Earth due to the accumulation of greenhouse gases", hint2: "It causes global warming and affects climate patterns" },
    { word: "zero waste", hint: "A philosophy that aims to reduce waste to a minimum by reusing and recycling", hint2: "It focuses on reducing, reusing, and recycling materials" },
    { word: "water pollution", hint: "Contamination of water bodies due to harmful substances", hint2: "It affects aquatic life and human health" },
    { word: "air pollution", hint: "Contamination of the atmosphere with harmful gases and particulates", hint2: "It causes respiratory diseases and environmental damage" },
    { word: "environmental policy", hint: "Regulations and strategies designed to manage and protect the environment", hint2: "It includes laws on pollution control, resource use, and conservation" }
];
