const words = [
    { word: "astronomy", hint: "The study of celestial bodies like stars and planets", hint2: "Science that deals with space and the universe" },
    { word: "planet", hint: "A large celestial body that orbits a star", hint2: "A spherical object in space like Earth or Mars" },
    { word: "universe", hint: "All of space and everything in it", hint2: "The vast expanse that includes all matter and energy" },
    { word: "galaxy", hint: "A large system of stars, gas, and dust", hint2: "A collection of stars bound together by gravity" },
    { word: "telescope", hint: "An instrument used to observe distant objects in space", hint2: "Optical device for viewing celestial bodies" },
    { word: "satellite", hint: "An object that orbits a planet or star", hint2: "Man-made or natural body orbiting a planet or moon" },
    { word: "spacecraft", hint: "A vehicle designed for travel in space", hint2: "Human-made vehicle used for exploration beyond Earth" },
    { word: "space mission", hint: "An operation aimed at exploring space", hint2: "A planned journey to study celestial bodies" },
    { word: "cosmos", hint: "The universe considered as a whole", hint2: "Everything that exists in space, including galaxies and stars" },
    { word: "solar system", hint: "A system of planets and other objects orbiting the Sun", hint2: "The Sun and the planets, moons, and other bodies that revolve around it" },
    { word: "orbit", hint: "The path that a celestial body follows around another", hint2: "The curved trajectory of an object in space due to gravity" },
    { word: "gravity", hint: "The force that attracts objects towards one another", hint2: "The force that holds planets and stars in place" },
    { word: "astronaut", hint: "A person trained to travel and work in space", hint2: "A scientist or engineer who participates in space missions" },
    { word: "launch", hint: "The act of sending a spacecraft or satellite into space", hint2: "The beginning of a journey into space from Earth" },
    { word: "rocket", hint: "A vehicle propelled by engines that expel gas at high speed", hint2: "Used to launch satellites, astronauts, or spacecraft into space" },
    { word: "space station", hint: "A large spacecraft designed for humans to live in space", hint2: "A facility in space for astronauts to conduct experiments and stay" },
    { word: "Mars", hint: "The fourth planet from the Sun, known as the Red Planet", hint2: "A rocky planet with a reddish appearance due to iron oxide" },
    { word: "moon", hint: "A natural satellite of a planet", hint2: "An object that orbits a planet, like Earth's Moon" },
    { word: "black hole", hint: "A region of space where gravity is so strong that nothing can escape", hint2: "A collapsed star with an immense gravitational pull" },
    { word: "nebula", hint: "A cloud of gas and dust in space, often a star formation site", hint2: "An interstellar cloud that may form new stars" },
    { word: "comet", hint: "A small icy body that orbits the Sun", hint2: "A celestial object that forms a bright coma when near the Sun" },
    { word: "asteroid", hint: "A small rocky object that orbits the Sun", hint2: "Smaller than a planet but larger than a meteor" },
    { word: "eclipse", hint: "The blocking of light from one celestial body by another", hint2: "When one celestial body passes in front of another, casting a shadow" },
    { word: "constellation", hint: "A group of stars forming a recognizable pattern", hint2: "A pattern of stars often named after animals or mythological figures" },
    { word: "space exploration", hint: "The use of astronomy and space technology to explore outer space", hint2: "Investigation of space beyond Earth through spacecraft or telescopes" },
    { word: "light year", hint: "A unit of distance that light travels in one year", hint2: "Measures the vast distances in space, equivalent to about 9.46 trillion kilometers" },
    { word: "satellite", hint: "A man-made object launched into orbit", hint2: "Used for communication, weather observation, and research in space" },
    { word: "milky way", hint: "The galaxy that contains our solar system", hint2: "A spiral galaxy with a large central bulge and several arms" },
    { word: "venus", hint: "The second planet from the Sun, often called Earth's twin", hint2: "A planet with a thick atmosphere and surface temperatures hot enough to melt lead" },
    { word: "Saturn", hint: "The sixth planet from the Sun, known for its extensive ring system", hint2: "A gas giant with over 80 moons" }
];

