const wordList = [
    { word: "metals", hint: "Elements that are good conductors of heat and electricity" },
    { word: "nonmetals", hint: "Elements that are poor conductors of heat and electricity" },
    { word: "malleable", hint: "Property of metals that allows them to be hammered into thin sheets" },
    { word: "ductile", hint: "Property of metals that allows them to be drawn into wires" },
    { word: "lustrous", hint: "Shiny appearance, a characteristic property of metals" },
    { word: "brittle", hint: "Property of nonmetals that makes them break easily under pressure" },
    { word: "sonorous", hint: "Property of metals that makes them produce sound when struck" },
    { word: "conductors", hint: "Materials that allow heat or electricity to pass through them" },
    { word: "insulators", hint: "Materials that do not allow heat or electricity to pass through them" },
    { word: "alloys", hint: "Mixtures of two or more metals or a metal with a nonmetal" },
    { word: "oxide", hint: "Compound formed when a metal or nonmetal reacts with oxygen" },
    { word: "reactivity", hint: "The tendency of an element to undergo chemical reactions" },
    { word: "displacement", hint: "Reaction where a more reactive metal replaces a less reactive one" },
    { word: "rusting", hint: "Corrosion of iron in the presence of air and water" },
    { word: "corrosion", hint: "Gradual deterioration of metals due to chemical reactions" },
    { word: "galvanization", hint: "Coating iron with zinc to prevent rusting" },
    { word: "anodizing", hint: "Process of forming a protective oxide layer on metals" },
    { word: "alkali", hint: "Metals from Group 1 that react vigorously with water" },
    { word: "alkaline", hint: "Metals from Group 2 of the periodic table" },
    { word: "transition", hint: "Metals that have variable oxidation states and form colored compounds" },
    { word: "metalloids", hint: "Elements with properties of both metals and nonmetals" },
    { word: "carbon", hint: "A nonmetal that exists in different forms like diamond and graphite" },
    { word: "sodium", hint: "A highly reactive alkali metal stored in kerosene" },
    { word: "magnesium", hint: "A metal that burns with a bright white flame" },
    { word: "calcium", hint: "An alkaline earth metal essential for bones and teeth" },
    { word: "zinc", hint: "A metal used in galvanization and dry cells" },
    { word: "copper", hint: "A metal commonly used in electrical wiring" },
    { word: "aluminium", hint: "A lightweight metal used in making utensils and aircraft" },
    { word: "gold", hint: "A precious metal that is highly malleable and ductile" },
    { word: "silver", hint: "A metal used in jewelry and mirrors" },
    { word: "platinum", hint: "A precious metal known for its corrosion resistance" },
    { word: "chlorine", hint: "A nonmetal used in water purification" },
    { word: "sulphur", hint: "A yellow nonmetal used in the manufacture of sulfuric acid" },
    { word: "iodine", hint: "A nonmetal used as an antiseptic" },
    { word: "graphite", hint: "A form of carbon that is a good conductor of electricity" },
    { word: "diamond", hint: "The hardest natural substance, a form of carbon" },
    { word: "hydrogen", hint: "A nonmetal that is highly flammable and used as a fuel" },
    { word: "oxidation", hint: "Reaction where a metal loses electrons" },
    { word: "reduction", hint: "Reaction where a metal gains electrons" },
    { word: "electrolysis", hint: "Process used to extract metals from their ores" },
    { word: "ores", hint: "Minerals from which metals are extracted" },
    { word: "smelting", hint: "Process of extracting metal from its ore by heating" },
    { word: "electroplating", hint: "Coating a metal object with another metal using electricity" },
    { word: "reactivity series", hint: "Arrangement of metals in order of their reactivity" },
    { word: "amphoteric", hint: "Metals that react with both acids and bases" },
    { word: "alkali metals", hint: "Group 1 elements known for their high reactivity" },
    { word: "acidic oxides", hint: "Oxides of nonmetals that dissolve in water to form acids" },
    { word: "basic oxides", hint: "Oxides of metals that dissolve in water to form bases" },
    { word: "neutral oxides", hint: "Oxides that are neither acidic nor basic" },
    { word: "silicon", hint: "A metalloid used in semiconductors" },
    { word: "phosphorus", hint: "A nonmetal used in fertilizers and matchsticks" }
];
