const words = [
    { word: "reproduction", hint: "Biological process by which new organisms are produced", hint2: "Can be sexual or asexual" },
    { word: "asexual reproduction", hint: "Reproduction without fusion of gametes", hint2: "Involves a single parent and results in offspring identical to the parent" },
    { word: "sexual reproduction", hint: "Reproduction involving fusion of male and female gametes", hint2: "Results in offspring with genetic variation" },
    { word: "gametes", hint: "Reproductive cells involved in sexual reproduction", hint2: "Includes sperm and egg cells" },
    { word: "fertilization", hint: "Process of fusion of male and female gametes", hint2: "Leads to the formation of a zygote" },
    { word: "zygote", hint: "Fertilized egg cell", hint2: "Results from the union of sperm and egg" },
    { word: "embryo", hint: "Early developmental stage of an organism", hint2: "Formed from the zygote after several cell divisions" },
    { word: "gestation", hint: "Developmental period of the embryo inside the mother's body", hint2: "In humans, it lasts approximately nine months" },
    { word: "ovary", hint: "Female reproductive organ that produces eggs", hint2: "Also produces hormones like estrogen and progesterone" },
    { word: "testes", hint: "Male reproductive organ that produces sperm", hint2: "Also produces the hormone testosterone" },
    { word: "menstruation", hint: "Monthly shedding of the uterine lining in females", hint2: "Part of the menstrual cycle" },
    { word: "puberty", hint: "Stage of physical and hormonal changes leading to sexual maturity", hint2: "Includes the development of secondary sexual characteristics" },
    { word: "ovulation", hint: "Release of an egg from the ovary", hint2: "Occurs around the middle of the menstrual cycle" },
    { word: "fertility", hint: "Ability to produce offspring", hint2: "Depends on the health of reproductive organs and gametes" },
    { word: "contraception", hint: "Methods used to prevent pregnancy", hint2: "Includes birth control pills, condoms, and surgical methods" },
    { word: "pregnancy", hint: "Condition of carrying developing offspring within the body", hint2: "Begins after fertilization and ends with childbirth" },
    { word: "in-vitro fertilization", hint: "Assisted reproductive technology where fertilization occurs outside the body", hint2: "Embryos are later implanted in the uterus" },
    { word: "cloning", hint: "Process of creating an identical copy of an organism", hint2: "Involves creating a genetically identical organism" },
    { word: "biparental inheritance", hint: "Inheritance of traits from both parents", hint2: "Involves the contribution of genes from both the mother and father" },
    { word: "sexual dimorphism", hint: "Differences in physical characteristics between male and female organisms", hint2: "Includes differences in size, coloration, and behavior" },
    { word: "pollination", hint: "Transfer of pollen from male to female reproductive parts in plants", hint2: "Can be done by wind, water, or insects" },
    { word: "germination", hint: "Process by which a seed develops into a new plant", hint2: "Requires water, warmth, and oxygen" },
    { word: "flower", hint: "Reproductive organ of flowering plants", hint2: "Contains male and/or female reproductive structures" },
    { word: "sexual reproduction in plants", hint: "Involves the formation of seeds", hint2: "Can occur through pollination and fertilization" },
    { word: "pollen", hint: "Male gametes in plants", hint2: "Transferred to female parts for fertilization" },
    { word: "ovule", hint: "Female gametes in plants", hint2: "Fertilized by pollen to form seeds" },
    { word: "seed", hint: "Matured ovule that contains the embryo", hint2: "Develops into a new plant" },
    { word: "reproductive health", hint: "State of physical, mental, and social well-being related to reproduction", hint2: "Involves education, prevention, and care related to reproductive organs" },
    { word: "sexually transmitted diseases", hint: "Diseases spread through sexual contact", hint2: "Includes HIV, gonorrhea, and syphilis" },
    { word: "adolescence", hint: "Stage of development between childhood and adulthood", hint2: "Characterized by puberty and significant physical and emotional changes" },
    { word: "chromosome", hint: "Thread-like structures containing genetic information", hint2: "Humans have 46 chromosomes in total, arranged in 23 pairs" },
    { word: "genes", hint: "Units of heredity that are passed from parents to offspring", hint2: "Located on chromosomes and determine traits" },
    { word: "mutation", hint: "Change in the DNA sequence", hint2: "Can lead to new traits or diseases" },
    { word: "genetic variation", hint: "Differences in the genetic makeup of individuals", hint2: "Occurs through sexual reproduction and mutations" },
    { word: "hormones", hint: "Chemical messengers that regulate body functions", hint2: "Includes estrogen, testosterone, and progesterone" },
    { word: "sterility", hint: "Inability to reproduce", hint2: "Can be caused by various medical conditions" },
    { word: "infertility", hint: "Inability to conceive after a year of trying", hint2: "Can be treated with medical interventions like IVF" },
    { word: "contraceptive methods", hint: "Techniques used to avoid pregnancy", hint2: "Includes condoms, pills, and intrauterine devices (IUDs)" }
];
