const words = [
    { word: "nutrition", hint: "Process by which organisms obtain and use food", hint2: "Involves ingestion, digestion, absorption, and assimilation" },
    { word: "respiration", hint: "Process by which organisms release energy from food", hint2: "Involves intake of oxygen and release of carbon dioxide" },
    { word: "circulation", hint: "Movement of blood through the body", hint2: "Helps transport oxygen, nutrients, and waste products" },
    { word: "excretion", hint: "Removal of metabolic waste from the body", hint2: "Involves organs like kidneys, lungs, and skin" },
    { word: "coordination", hint: "Process by which organisms respond to stimuli", hint2: "Involves nervous and endocrine systems for control" },
    { word: "enzyme", hint: "Biological catalyst that speeds up reactions", hint2: "Helps in digestion by breaking down large molecules" },
    { word: "digestion", hint: "Breaking down of food into simpler molecules", hint2: "Occurs in the digestive system, involving mechanical and chemical processes" },
    { word: "absorption", hint: "Process of taking in nutrients from digested food", hint2: "Mainly occurs in the small intestine" },
    { word: "assimilation", hint: "Incorporation of absorbed nutrients into the body", hint2: "Nutrients are used for growth, repair, and energy" },
    { word: "transport", hint: "Movement of substances within an organism", hint2: "Involves circulatory systems like blood and vascular tissues" },
    { word: "respiratory system", hint: "System responsible for gas exchange", hint2: "Includes organs like lungs, trachea, and diaphragm" },
    { word: "circulatory system", hint: "System that transports blood and lymph", hint2: "Includes heart, blood vessels, and blood" },
    { word: "heart", hint: "Muscular organ that pumps blood through the body", hint2: "Divided into four chambers: two atria and two ventricles" },
    { word: "blood", hint: "Fluid that circulates through the body", hint2: "Carries oxygen, nutrients, and waste products" },
    { word: "kidney", hint: "Organ responsible for filtering waste from blood", hint2: "Helps maintain water and electrolyte balance in the body" },
    { word: "urinary system", hint: "System that removes waste products via urine", hint2: "Includes kidneys, ureters, bladder, and urethra" },
    { word: "gills", hint: "Respiratory organs found in fish", hint2: "Used to extract oxygen from water" },
    { word: "lungs", hint: "Main respiratory organs in terrestrial animals", hint2: "Facilitate gas exchange of oxygen and carbon dioxide" },
    { word: "stomata", hint: "Small openings on plant leaves", hint2: "Regulate gas exchange and water loss in plants" },
    { word: "chlorophyll", hint: "Pigment responsible for photosynthesis in plants", hint2: "Absorbs light energy, mostly from blue and red light" },
    { word: "photosynthesis", hint: "Process by which plants make food using sunlight", hint2: "Involves carbon dioxide, water, and light energy" },
    { word: "chloroplast", hint: "Organelle where photosynthesis occurs in plants", hint2: "Contains chlorophyll and other pigments" },
    { word: "alveoli", hint: "Tiny air sacs in the lungs", hint2: "Site of gas exchange between air and blood" },
    { word: "capillary", hint: "Smallest type of blood vessel", hint2: "Facilitates exchange of gases, nutrients, and waste between blood and tissues" },
    { word: "vein", hint: "Blood vessel that carries blood towards the heart", hint2: "Has valves to prevent backflow of blood" },
    { word: "artery", hint: "Blood vessel that carries blood away from the heart", hint2: "Thick-walled and carries oxygenated blood (except pulmonary artery)" },
    { word: "respiratory surface", hint: "Site where gas exchange occurs", hint2: "In humans, this is the alveoli in the lungs" },
    { word: "pulmonary system", hint: "Circulatory system that serves the lungs", hint2: "Involves the pulmonary arteries and veins" },
    { word: "systemic circulation", hint: "Circulation of blood through the body", hint2: "Carries oxygenated blood from the heart to the rest of the body" },
    { word: "pneumonia", hint: "Infection that causes inflammation in the lungs", hint2: "Can affect gas exchange in the alveoli" },
    { word: "asthma", hint: "Condition that causes difficulty in breathing", hint2: "Involves inflammation and narrowing of airways" },
    { word: "exhalation", hint: "Process of breathing out air", hint2: "Involves releasing carbon dioxide from the lungs" },
    { word: "inhalation", hint: "Process of breathing in air", hint2: "Involves drawing in oxygen into the lungs" },
    { word: "respiratory pigment", hint: "Molecule that helps in oxygen transport", hint2: "Hemoglobin in blood is an example" },
    { word: "blood pressure", hint: "Pressure exerted by blood on the walls of blood vessels", hint2: "Measured using systolic and diastolic readings" },
    { word: "diastole", hint: "Phase when the heart relaxes", hint2: "Allows chambers to fill with blood" },
    { word: "systole", hint: "Phase when the heart contracts", hint2: "Pumps blood out of the heart to the body" }
];
