const wordList = [
    { word: "carbon", hint: "Element found in all living organisms" },
    { word: "graphite", hint: "A soft form of carbon used as a lubricant and in pencils" },
    { word: "diamond", hint: "A hard form of carbon used in jewelry and cutting tools" },
    { word: "allotropes", hint: "Different forms of the same element, like carbon" },
    { word: "carbon dioxide", hint: "A gas produced by combustion and respiration" },
    { word: "carbon monoxide", hint: "A toxic gas formed by incomplete combustion" },
    { word: "hydrocarbons", hint: "Compounds made up of hydrogen and carbon" },
    { word: "methane", hint: "A simple hydrocarbon and greenhouse gas" },
    { word: "ethane", hint: "A saturated hydrocarbon with two carbon atoms" },
    { word: "propane", hint: "A hydrocarbon commonly used as fuel for cooking" },
    { word: "alkanes", hint: "Saturated hydrocarbons with single bonds" },
    { word: "alkenes", hint: "Unsaturated hydrocarbons with double bonds" },
    { word: "alkynes", hint: "Unsaturated hydrocarbons with triple bonds" },
    { word: "organic", hint: "Compounds primarily composed of carbon and hydrogen" },
    { word: "isomerism", hint: "Compounds with the same formula but different structures" },
    { word: "ethanol", hint: "An alcohol used in hand sanitizers and beverages" },
    { word: "acetone", hint: "A solvent used in nail polish remover" },
    { word: "carboxylic", hint: "Compounds containing the -COOH group" },
    { word: "esters", hint: "Sweet-smelling compounds used in perfumes" },
    { word: "aldehydes", hint: "Compounds containing the -CHO group" },
    { word: "ketones", hint: "Compounds with a carbonyl group bonded to two carbon atoms" },
    { word: "benzene", hint: "An aromatic hydrocarbon with a ring structure" },
    { word: "toluene", hint: "A derivative of benzene used as a solvent" },
    { word: "polymers", hint: "Large molecules made of repeating units" },
    { word: "plastic", hint: "A synthetic polymer commonly used in daily life" },
    { word: "nylon", hint: "A synthetic fiber made from carbon compounds" },
    { word: "graphene", hint: "A single layer of carbon atoms with extraordinary strength" },
    { word: "fullerenes", hint: "Molecules of carbon shaped like spheres or tubes" },
    { word: "carbon cycle", hint: "The process of carbon movement in the environment" },
    { word: "fossil fuels", hint: "Energy sources like coal, oil, and natural gas" },
    { word: "combustion", hint: "Burning of carbon compounds to produce energy" },
    { word: "photosynthesis", hint: "Process by which plants use carbon dioxide to make food" },
    { word: "fermentation", hint: "A process that produces alcohol from sugars" },
    { word: "charcoal", hint: "A form of carbon used as fuel and in filtration" },
    { word: "sublimation", hint: "Change of a solid like dry ice (solid CO2) to gas" },
    { word: "carbonates", hint: "Compounds reacting with acids to form carbon dioxide" },
    { word: "bicarbonates", hint: "Intermediate forms in the carbon cycle, like baking soda" },
    { word: "chloroform", hint: "A carbon compound used as an anesthetic in the past" },
    { word: "vinegar", hint: "A solution of acetic acid, a carbon compound" },
    { word: "amino acids", hint: "Building blocks of proteins containing carbon" },
    { word: "urea", hint: "A nitrogen-carbon compound excreted by animals" },
    { word: "biogas", hint: "Methane-rich fuel produced from organic waste" },
    { word: "carbon footprint", hint: "Measure of carbon emissions by human activities" },
    { word: "soot", hint: "Carbon particles produced by incomplete combustion" }
];
