const wordList = [
    { word: "periodic", hint: "Recurring trends in element properties in the periodic table" },
    { word: "table", hint: "Organized chart of all known chemical elements" },
    { word: "groups", hint: "Vertical columns in the periodic table" },
    { word: "periods", hint: "Horizontal rows in the periodic table" },
    { word: "metals", hint: "Elements that are good conductors of heat and electricity" },
    { word: "nonmetals", hint: "Elements that are poor conductors of heat and electricity" },
    { word: "metalloids", hint: "Elements with properties of both metals and nonmetals" },
    { word: "alkali", hint: "Group 1 elements, highly reactive metals" },
    { word: "alkaline", hint: "Group 2 elements, reactive but less than alkali metals" },
    { word: "halogens", hint: "Group 17 elements, highly reactive nonmetals" },
    { word: "noble", hint: "Group 18 gases, chemically inert" },
    { word: "lanthanides", hint: "Elements from atomic numbers 57 to 71" },
    { word: "actinides", hint: "Elements from atomic numbers 89 to 103, mostly radioactive" },
    { word: "transition", hint: "Elements in groups 3 to 12, known for forming colorful compounds" },
    { word: "periodicity", hint: "Repeating patterns in the periodic table" },
    { word: "atomic", hint: "Referring to the structure or size of an atom" },
    { word: "radius", hint: "The size of an atom from its nucleus to its outermost shell" },
    { word: "ionization", hint: "Energy required to remove an electron from an atom" },
    { word: "electronegativity", hint: "An atom's ability to attract shared electrons" },
    { word: "valency", hint: "Combining power of an element based on its electrons" },
    { word: "dobereiner", hint: "Proposed the law of triads for element classification" },
    { word: "newlands", hint: "Gave the law of octaves in the periodic table" },
    { word: "mendeleev", hint: "Father of the periodic table, arranged elements by atomic mass" },
    { word: "modern", hint: "Periodic table arranged by atomic number" },
    { word: "atomicnumber", hint: "The number of protons in an atom's nucleus" },
    { word: "massnumber", hint: "The total number of protons and neutrons in an atom" },
    { word: "isotopes", hint: "Atoms of the same element with different mass numbers" },
    { word: "isobars", hint: "Atoms with the same mass number but different atomic numbers" },
    { word: "d-block", hint: "Transition metals in the center of the periodic table" },
    { word: "s-block", hint: "Elements in groups 1 and 2" },
    { word: "p-block", hint: "Groups 13 to 18 elements with diverse properties" },
    { word: "f-block", hint: "Lanthanides and actinides, often placed below the main table" },
    { word: "reactivity", hint: "How readily an element reacts with others" },
    { word: "electrons", hint: "Negatively charged particles in an atom" },
    { word: "protons", hint: "Positively charged particles in the nucleus" },
    { word: "neutrons", hint: "Neutral particles in the atom's nucleus" },
    { word: "hydrogen", hint: "The lightest and simplest element" },
    { word: "helium", hint: "Noble gas with atomic number 2" },
    { word: "chlorine", hint: "A halogen used in water purification" },
    { word: "argon", hint: "A noble gas used in light bulbs" },
    { word: "fluorine", hint: "Most electronegative element" },
    { word: "magnesium", hint: "An alkaline earth metal in group 2" },
    { word: "calcium", hint: "Essential alkaline earth metal for bones" },
    { word: "iron", hint: "Transition metal, key in hemoglobin" },
    { word: "gold", hint: "Noble transition metal, highly unreactive" },
    { word: "carbon", hint: "Basis of organic chemistry" },
    { word: "nitrogen", hint: "Element forming 78% of Earth's atmosphere" },
    { word: "oxygen", hint: "Essential for respiration" },
    { word: "silicon", hint: "A metalloid used in semiconductors" },
    { word: "zinc", hint: "Transition metal used for galvanization" },
    { word: "copper", hint: "Good conductor used in wiring" }
];
