const wordList = [
    { word: "acid", hint: "Substance with a pH less than 7" },
    { word: "base", hint: "Substance with a pH greater than 7" },
    { word: "neutral", hint: "Substance with a pH of 7" },
    { word: "indicator", hint: "Used to test acids and bases" },
    { word: "litmus", hint: "A common natural indicator" },
    { word: "phenolphthalein", hint: "An indicator that turns pink in basic solutions" },
    { word: "methylorange", hint: "Indicator that turns red in acidic solutions" },
    { word: "pH", hint: "Scale to measure acidity or alkalinity" },
    { word: "salt", hint: "Formed when acid reacts with base" },
    { word: "alkali", hint: "A base that dissolves in water" },
    { word: "neutralization", hint: "Reaction between acid and base" },
    { word: "strongacid", hint: "Acid that ionizes completely in water" },
    { word: "weakacid", hint: "Acid that partially ionizes in water" },
    { word: "strongbase", hint: "Base that ionizes completely in water" },
    { word: "weakbase", hint: "Base that partially ionizes in water" },
    { word: "hydrochloric", hint: "Strong acid with the formula HCl" },
    { word: "sulfuric", hint: "Strong acid used in batteries" },
    { word: "nitric", hint: "Strong acid used in fertilizers" },
    { word: "acetic", hint: "Weak acid found in vinegar" },
    { word: "citric", hint: "Acid naturally present in citrus fruits" },
    { word: "tartaric", hint: "Acid used in baking powder" },
    { word: "sodiumhydroxide", hint: "Strong base also called caustic soda" },
    { word: "potassiumhydroxide", hint: "Strong base used in soap making" },
    { word: "ammoniumhydroxide", hint: "Weak base used in cleaning agents" },
    { word: "calciumhydroxide", hint: "Common name is slaked lime" },
    { word: "magnesiumhydroxide", hint: "Base used as an antacid" },
    { word: "limewater", hint: "Solution of calcium hydroxide in water" },
    { word: "bleaching", hint: "Chemical process for whitening substances" },
    { word: "plasterofparis", hint: "Quick-setting material from gypsum" },
    { word: "gypsum", hint: "Mineral used to make plaster of Paris" },
    { word: "baking", hint: "Powder that releases CO2 during baking" },
    { word: "washing", hint: "Powder used for cleaning clothes" },
    { word: "carbonate", hint: "Reacts with acids to release CO2" },
    { word: "bicarbonate", hint: "Another name for baking soda" },
    { word: "chloride", hint: "Ion present in table salt" },
    { word: "sodiumchloride", hint: "Chemical name of table salt" },
    { word: "calciumcarbonate", hint: "Main component of limestone" },
    { word: "ammonia", hint: "Compound with a strong pungent smell" },
    { word: "soap", hint: "Cleansing agent made from fats and alkali" },
    { word: "detergent", hint: "Synthetic cleaning agent" },
    { word: "brine", hint: "Concentrated solution of salt in water" },
    { word: "electrolysis", hint: "Process used to break down brine" },
    { word: "chlorine", hint: "Gas used for water purification" },
    { word: "hydrogen", hint: "Gas released when acid reacts with metal" },
    { word: "acidrain", hint: "Caused by the reaction of pollutants with water" },
    { word: "alkalinity", hint: "Measure of the strength of a base" },
    { word: "neutralize", hint: "To cancel out acidity or alkalinity" },
    { word: "effervescence", hint: "Bubbles formed during a reaction" },
    { word: "amphoteric", hint: "Substance that reacts with both acids and bases" },
    { word: "zincoxide", hint: "Amphoteric oxide used in ointments" },
    { word: "aluminumoxide", hint: "Amphoteric oxide used in ceramics" },
    { word: "concentration", hint: "Amount of solute in a solution" },
    { word: "dilution", hint: "Adding water to reduce concentration" },
    { word: "crystallization", hint: "Process of forming solid crystals" },
    { word: "acidic", hint: "Having properties of an acid" },
    { word: "basic", hint: "Having properties of a base" },
    { word: "neutral", hint: "Neither acidic nor basic" }
];
