const wordList = [
    { word: "reaction", hint: "A process in which substances are transformed into new substances" },
    { word: "reactant", hint: "The starting substance in a chemical reaction" },
    { word: "product", hint: "The substance formed as a result of a chemical reaction" },
    { word: "equation", hint: "Representation of a chemical reaction using symbols and formulas" },
    { word: "symbol", hint: "A shorthand representation of an element" },
    { word: "formula", hint: "Representation of a compound using symbols and subscripts" },
    { word: "balanced", hint: "A chemical equation where atoms are equal on both sides" },
    { word: "unbalanced", hint: "An equation where atoms on reactant and product sides differ" },
    { word: "combination", hint: "Reaction where two substances combine to form one product" },
    { word: "decomposition", hint: "Breaking down a compound into simpler substances" },
    { word: "displacement", hint: "Reaction where one element replaces another in a compound" },
    { word: "double", hint: "Exchange of ions between two compounds" },
    { word: "neutralization", hint: "Reaction between acid and base to form salt and water" },
    { word: "oxidation", hint: "Reaction involving the gain of oxygen or loss of electrons" },
    { word: "reduction", hint: "Reaction involving the loss of oxygen or gain of electrons" },
    { word: "precipitate", hint: "Insoluble solid formed in a chemical reaction" },
    { word: "endothermic", hint: "Reaction that absorbs heat energy" },
    { word: "exothermic", hint: "Reaction that releases heat energy" },
    { word: "catalyst", hint: "A substance that speeds up a reaction without getting consumed" },
    { word: "rusting", hint: "Corrosion of iron in the presence of air and water" },
    { word: "corrosion", hint: "Deterioration of metals due to chemical reactions" },
    { word: "electrolysis", hint: "Decomposition of a compound using electric current" },
    { word: "conservation", hint: "Law stating that mass is neither created nor destroyed" },
    { word: "thermal", hint: "Reaction initiated by heat energy" },
    { word: "photochemical", hint: "Reaction initiated by light energy" },
    { word: "change", hint: "Can be chemical or physical transformation" },
    { word: "effervescence", hint: "Formation of bubbles in a liquid during a reaction" },
    { word: "atoms", hint: "Smallest unit of matter participating in reactions" },
    { word: "molecule", hint: "A group of atoms bonded together" },
    { word: "ions", hint: "Charged particles formed in ionic reactions" },
    { word: "oxygen", hint: "Gas essential for combustion reactions" },
    { word: "hydrogen", hint: "Gas released when metal reacts with acid" },
    { word: "salt", hint: "Formed in neutralization reactions" },
    { word: "water", hint: "Product in combustion of hydrocarbons" },
    { word: "combustion", hint: "Reaction of a substance with oxygen, releasing heat" },
    { word: "lime", hint: "Calcium oxide, used in some decomposition reactions" },
    { word: "carbon", hint: "Element found in all living organisms" },
    { word: "reactions", hint: "Processes classified as endothermic or exothermic" },
    { word: "silver", hint: "A metal prone to tarnishing" },
    { word: "copper", hint: "A metal used in electrical wiring" },
    { word: "acids", hint: "Substances with a pH less than 7" },
    { word: "bases", hint: "Substances with a pH greater than 7" },
    { word: "neutral", hint: "Substance with a pH of 7" },
    { word: "indicator", hint: "Used to test acids and bases" },
    { word: "litmus", hint: "Common indicator for acids and bases" },
    { word: "pH", hint: "Scale to measure acidity or alkalinity" },
    { word: "metals", hint: "Elements that are good conductors of heat and electricity" },
    { word: "corrosion", hint: "Process that damages metals like iron" },
    { word: "oxidizing", hint: "Agent that oxidizes others and gets reduced" },
    { word: "reducing", hint: "Agent that reduces others and gets oxidized" },
    { word: "carbonates", hint: "Compounds reacting with acids to release CO2" },
    { word: "calcium", hint: "Essential element for bones and chemical reactions" },
    { word: "effusion", hint: "Release of gas during a reaction" },
    { word: "magnesium", hint: "Burns with a bright white flame" },
    { word: "chloride", hint: "Ion commonly found in table salt" },
    { word: "precipitation", hint: "Formation of a solid in a reaction" },
    { word: "hydroxide", hint: "Formed in the reaction of water and base" },
    { word: "alkali", hint: "A base that dissolves in water" },
    { word: "galvanization", hint: "Coating iron with zinc to prevent rust" },
    { word: "quicklime", hint: "Common name for calcium oxide" },
    { word: "slaked", hint: "Common name for calcium hydroxide" },
    { word: "photosynthesis", hint: "Reaction plants use to make food" },
    { word: "sublimation", hint: "Change of state from solid to gas directly" },
    { word: "ethanol", hint: "Common alcohol used in labs" },
    { word: "carbonates", hint: "React with acids to form carbon dioxide" }
];
